services:
  web:
    image: imadenos/fastapiwithnginx:latest
    container_name: fastapi-app
    restart: unless-stopped
    expose:
      - "8000"
  
  nginx:
      image: nginx:latest
      container_name: nginx-proxy
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - web