services:
  web:
    image: imadenos/fastapiwithnginx:latest
    container_name: fastapi-app
    ports:
      - "8000:8000"
    restart: unless-stopped
  
  nginx:
      restart: unless-stopped
      image: nginx
      container_name: nginx-proxy
      ports:
        - "81:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - web
      restart: unless-stopped